### ISSUE TITLE
consider removing Lazy support

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#101]
Or at least push it into the future releases.

It adds considerable API surface and even after reading docs like https://ravendb.net/docs/article-page/4.1/csharp/client-api/session/querying/how-to-perform-queries-lazily I can't quite see the scenario where this is beneficial.

**Comment by ayende** [comment]
Lazy is meant to reduce the number of calls you make to the database.
The idea is that you may package multiple operations into a single round trip.

Frex, using Go syntax:
```
lazyRecentOrders := session.lazy.query("from Orders where Owner = $me order by Date desc limit 5").with("me", "users/1-A").lazily()
lazyCart := session.lazy.query("from Carts where Owner = $me").lazilyFirst()

// No calls so far


err: = lazyCart.Value(&cart)

// here we call once

err = lazyRecentOrders.Value(&orders)
// no call here
```

**Comment by ayende** [comment]
This really help you when the database isn't nearby

**Comment by kjk** [comment]
Makes sense, thanks for the explanation. Will keep.
