### ISSUE TITLE
Refresh() twice should work

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#107]
Currently:
```
var u *User
session.Load(&u, id)
session.Refresh(u)  // works
session.Refresh(u) // returns an error
```

This matches (I think) Java behavior but seems wrong. Second `Refresh()` should work.

The reason for that is that in `refreshInternal()` instead of updating `documentInfo.entity` (which is the same object as `entity` argument to `Refresh()`) we create a new object, set it as the new `documentInfo.entity` and copy its properties to the entity.

The object we passed to `Refresh` is no longer recognized as being part of the session.

 To fix this, we should copy the properties of the new object to `documentInfo.entity`.

**Comment by gregolsky** [comment]
@kjk can you check if C# throws error on the second refresh? If not then it's a java (and node.js) bug

**Comment by kjk** [comment]
Sorry, I don't have a C# setup.

**Comment by ml054** [comment]
I think refresh should be idempotent operation. We should check c# then. I will do that today and let you know.

**Comment by ml054** [comment]
It works in c#, so we have to fix that in other clients:

```
  [Fact]
        public void RefreshTwice()
        {
            using (var store = GetDocumentStore())
            {
                var index = new ReduceMeByTag();
                store.ExecuteIndex(index);
                using (var session = store.OpenSession())
                {
                    session.Store(new ReduceMe
                    {
                        Id = "reduce/1",
                        Tag = "Foo",
                        Amount = 2
                    });
                    session.SaveChanges();
                }
                
                using (var session = store.OpenSession())
                {

                    var a = session.Load<ReduceMe>("reduce/1");
                    
                    session.Advanced.Refresh(a);
                    session.Advanced.Refresh(a);
                }
            }
        }
```

**Comment by ml054** [comment]
created issue: https://issues.hibernatingrhinos.com/issue/RDBC-264
