### ISSUE TITLE
Configure travis ci and appveyor for replication tests

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#110]
I don't have permission to do that.

AppVeyor: https://ci.appveyor.com/project/ravendb/ravendb-go-client
Travis: https://travis-ci.org/ravendb/ravendb-go-client

In order to run replication tests we need a valid license.

Both travis and appveyor need to have `RAVEN_License` env variable set to a valid dev license. I assume that's the same setup as java client on travis.

**Comment by gregolsky** [comment]
Added RAVEN_License var on travis and appveyor. Can you verify please?

**Comment by kjk** [comment]
Error on travis. https://travis-ci.org/ravendb/ravendb-go-client/builds/486285061
```
$ export RAVEN_License=[secure]
The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys.
```

**Comment by kjk** [comment]
Looks good on AppVeyor

**Comment by kjk** [comment]
Looks good, thanks!
