### ISSUE TITLE
tests for cluster setup

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#129]
Current tests don't exercise the code paths related to a multi-node setup (i.e. a cluster). Things like picking the fastest node, handling failed nodes etc.

Given that they involve concurrency it's highly probable that they are buggy and have race conditions.

Therefore it would be nice to have a test that exercises those code paths. Can this be done by creating a multi-node cluster on the same computer by running multiple server executables on different ports?

Those could even be special tests that are only run occasionally, given that to flesh out concurrency bugs / data races it would be good to run the test for a long time and force adding new nodes, failing nodes in the cluster etc. to exercise those rare code paths.

**Comment by ayende** [comment]
Yes, you can spin up three nodes and make a cluster on the same machine.
Can run on different ports or bind to `127.0.0.1`, `127.0.0.2`, etc.

**Comment by ayende** [comment]
In fact, I would prefer if by default we'll run all the tests in this manner. Tests that don't have any cluster work will still run in a cluster just fine, after all

**Comment by kjk** [comment]
we're now starting 3 servers and randomly selecting read balancing behavior to hopefully start exercising more codepaths
