### ISSUE TITLE
Setup Travis and Appveyor on Raven account

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#13]
Now that we work on ravendb repo, you should login to ravendb's travis and appveyor accounts and enable the repo for tests and update the badges in readme.md

**Comment by gregolsky** [comment]
Here's Travis: https://travis-ci.org/ravendb/ravendb-go-client/builds
Don't think we need AppVeyor.

cc @iftahbe

**Comment by ppekrol** [comment]
@kjk why do we need both Travis and AppVeyor. From Configs it looks like Travis = Linux and AppVeyor = Windows. Can you confirm?

**Comment by kjk** [comment]
Yes, I enabled both because only AppVeyor can support Windows.

Travis runs Linux build.

It would also be good to have a Mac OS X CI. Circle CI has it but unlike Linux/Windows there is no free tier for open source.
