### ISSUE TITLE
Second thoughts on DatabaseChanges and subscriptions API

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#141]
The question is: is it better to have:
a) `func (c *DatabaseChanges) ForAllDocuments(cb func(*DocumentChange)) (CancelFunc, error)`
or
b) `func (c *DatabaseChanges) ForAllDocuments() (chan *DocumentChange, CancelFunc, error)`

I've implemented both versions, first a) and now we have b).

I lack experience in writing the client code to decide which is better for typical usage in the client.

Superficially, the tests became shorter with b). However, test code might be atypical in that we need to wait for notifications to verify we're getting them hence the need for goroutines/channels to convert notifications in a callback into a blocking queue.

In a way b) moves the construction of a blocking queue (a channel) into the driver code.

However, if a typical client of notifications doesn't require that then by giving them a channel we're forcing them to launch a goroutine to handle notifications.

A client can trivially convert a callback into a queue with channel send.

Leaving this as an open question for now.

**Comment by ayende** [comment]
Can you do this the other way? 
Something like: 
`func (c *DatabaseChanges) ForAllDocument(char*DocumentChange)`

Caller will construct the channel and owns it.
They can destroy the channel when needed and we'll respond by removing the subscription?

Does this make things easier from the POV of the client?

A typical case for handling this is to want to notify the user that a document they are editing changed.
I'm not sure if you'll use a channel for that (and then a websocket to notify the browser) or prefer a callback?

**Comment by kjk** [comment]
The important distinction is callbacks vs. channels. If we use channels, which side creates a channel is a minor distinctions (essentially moving one line of code from the driver code to client code).

To elaborate more on channels vs. callbacks.

Terminology: simplifying, a goroutine is a thread.

Channels imply concurrency. If we return a channel a client MUST launch a goroutine to read change notifications. Since there's no guarantee that a notification will ever come, if client just reads from a channel on main goroutine it might block forever.

While there is concurrency inside the driver (internally we launch goroutine to maintain network connection to the server) it could be considered an implementation detail.

A callback would be handled on a goroutine owned by driver code. Safety-wise both cases need to be aware that any use is concurrent.

A callback can be easily converted to a channel, which is what we were doing in tests. Using callbacks doesn't preclude the client from using channels/concurrency and it doesn't "force" to use concurrency.

There doesn't seem to be clearly "most common" way of doing that.

Callbacks don't seem very go-ish but at the same time they are used e.g. `filepath.Walk` in standard library traverses the filesystem and calls a callback for each file.

Postgres driver (https://godoc.org/github.com/lib/pq#hdr-Notifications) seems to be using a channel.

Mongodb driver (https://godoc.org/go.mongodb.org/mongo-driver/mongo#ChangeStream) seems to return an iterator.

A Go client for firebase (https://godoc.org/firebase.google.com/go/db#Client) seems to punt on this completely even though real-time notifications are a feature of firebase.

We use notification callbacks for several other "listening for changes" cases.

**Comment by ayende** [comment]
In that case, let's use a callback to be consistent with our other clients.
