### ISSUE TITLE
No results for field type ravendb.Time 

### ISSUE THREAD

**Issue by Danielle9897** [ravendb/ravendb-go-client#155]
For example - run a collection query on Employees collection:

```
queriedType := reflect.TypeOf(&Employee{})
fullCollectionQuery := session.QueryCollectionForType(queriedType)

var collectionResults []*Employee
fullCollectionQuery.GetResults(&collectionResults)
```

=> The resulting 'HiredAt' field - which is of type **ravendb.Time** - is empty ({})

**Comment by kjk** [comment]
I looked a bit more into this and there actually is no problem, it's just not displayed.

`HiredAt` is of type `ravendb.Time`, which is a custom type and `pretty.Print` doesn't know how to display it.

If we add:
```
		pretty.Print(queryResults[0])
		fmt.Printf("Hired at: %s\n", time.Time(queryResults[0].HiredAt))
```
It will show that `HiredAt` is correct:
```
{FullName:  "",
 FirstName: "Anne",
 Title:     "Sales Representative",
 HiredAt:   {}}
Hired at: 1994-11-15 00:00:00 +0000 UTC
```
