### ISSUE TITLE
Self Sign Certificate Error in Connect

### ISSUE THREAD

**Issue by MohMehrnia** [ravendb/ravendb-go-client#156]
When I use Self Sign Certificate for config ravendb and try connect them, show me bellow message:
The remote certificate is invalid according to the validation procedure

**Comment by ayende** [comment]
Are you sure that you are getting this on Go? This text usually come from .NET, no Go.
What is the full stack trace of the error?

**Comment by MohMehrnia** [comment]
Sorry for postring in the repository, i can not find suitable repository for .net clint
very sorry, by i need help

**Comment by ayende** [comment]
Based on your question on the mailing list, it is in .NET, closing this, then.h

**Comment by ayende** [comment]
Will answer in the mailing list.
