### ISSUE TITLE
json_operation.go - Issue with Savechanges when comparing document string properties that have changed

### ISSUE THREAD

**Issue by david-bergman** [ravendb/ravendb-go-client#162]
Hi,

I have picked up an issue when there is an existing document that has a string value set to null, and you then attempt to update the document by setting the property to a string. 

Error throws below, because "newProp", (which is incorrectly named as it is the old prop in terms of what is passed into this function) is nil. 

![image](https://user-images.githubusercontent.com/13984154/110936709-fe6f1780-8339-11eb-969b-ee1e7af6ca84.png)
![image](https://user-images.githubusercontent.com/13984154/110936740-0929ac80-833a-11eb-9942-07f225fbe9f8.png)

func isJSONStringEqual(oldPropVal string, newProp interface{}) bool {
	switch newPropVal := newProp.(type) {
	case string:
		return oldPropVal == newPropVal
	default:
		// TODO: can those happen in real life?
		panicIf(true, "unhandled type of newProp, expected 'string' and is '%T'", newProp)
	}
	return false
}

I would suggest adding a handler for the case where newProp is nil 

func isJSONStringEqual(oldPropVal string, newProp interface{}) bool {
	switch newPropVal := newProp.(type) {
	case string:
		return oldPropVal == newPropVal
        **case nil:
                return false** 
	default:
		// TODO: can those happen in real life?
		panicIf(true, "unhandled type of newProp, expected 'string' and is '%T'", newProp)
	}
	return false
}

??

**Comment by ayende** [comment]
Hi,
Can you add a test case showing the error?

**Comment by david-bergman** [comment]
[string_nil_save_changes_test.zip](https://github.com/ravendb/ravendb-go-client/files/6139687/string_nil_save_changes_test.zip)

**Comment by ayende** [comment]
Thanks, I'll push a fix in a few minutes.

**Comment by ayende** [comment]
Fixed in f43327b57a88ab5931012a163c340f6e5856b602
