### ISSUE TITLE
Time Parsing

### ISSUE THREAD

**Issue by bobmcallan** [ravendb/ravendb-go-client#163]
Hello,

I'm receiving an error when selecting time.Time / ravendb.Time fields. 

```
type User struct {
        UserID      int          `json:"user_id" gorm:"column:user_id"`
	CreatedAt   ravendb.Time `json:"created_at" gorm:"column:created_at"`
       ....
}
```

Trace: parsing time "" as "2006-01-02T15:04:05.9999999-07:00": cannot parse "" as "2006"

The insert/store completes as required, however fetch fails. 

`	var results []*models.User

	session, err := s.store.OpenSession("")

	if err != nil {
		return results, err
	}

	defer session.Close()

	q := session.QueryCollection("companies")

	q = paginate(page, size, q)

	err = q.GetResults(&results)
`
--- Full exception
Trace: parsing time "" as "2006-01-02T15:04:05.9999999-07:00": cannot parse "" as "2006"

C:/Program Files/Go/src/runtime/panic.go:965
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/util.go:22
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/time.go:78
C:/Program Files/Go/src/encoding/json/decode.go:860
C:/Program Files/Go/src/encoding/json/decode.go:384
C:/Program Files/Go/src/encoding/json/decode.go:765
C:/Program Files/Go/src/encoding/json/decode.go:370
C:/Program Files/Go/src/encoding/json/decode.go:180
C:/Program Files/Go/src/encoding/json/decode.go:107
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/json_util.go:33
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/reflect.go:292
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/entity_to_json.go:110
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/in_memory_document_session_operations.go:461
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/query_operation.go:172
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/query_operation.go:139
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/abstract_document_query.go:2243
C:/Matrak/src/pkg/mod/github.com/ravendb/ravendb-go-client@v0.0.0-20201105141604-5ff65ecb1354/abstract_document_query.go:2125
C:/Matrak/src/reducere/src/handlers/users.go:118
C:/Matrak/src/reducere/src/handlers/users.go:89
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352
C:/Matrak/src/reducere/src/main.go:199
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352
C:/Matrak/src/reducere/src/middleware/requestid/requestid.go:97
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352
C:/Matrak/src/reducere/src/main.go:216
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352
C:/Matrak/src/reducere/src/main.go:184
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/middleware/logger/logger.go:50
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1343
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1352
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/middleware/recover/recover.go:55
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1030
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/context/context.go:1217
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/handler.go:250
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:135
C:/Matrak/src/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/router/router.go:227
C:/Program Files/Go/src/net/http/server.go:2887
C:/Program Files/Go/src/net/http/server.go:1952
C:/Program Files/Go/src/runtime/asm_amd64.s:1371

Thanks,
Bob

**Comment by kjk** [comment]
What the error is saying is that the library tries to decode `CreatedAt` value from json response as time but the value is either missing or an empty string and therefore decoding fails since it's not a valid time represetation.

I assume `CreatedAt` should always be there so most likely the error happened during insertion and it only manifests itself during fetch so I would double-check the code that inserts the values.

You can double-check this theory by looking at those objects in the database.

**Comment by bobmcallan** [comment]
Yes, you are correct. I changed the type to a string and fetch works as required.

Is an option to have a nullable ravendb.Time type? or default value in the struct definition?

**Comment by ayende** [comment]
You can make that a reference, yes. 
```
type CustomerNilTime struct {
	ID        string        `json:"Id"`
	CreatedAt *ravendb.Time `json:"createdAt"`
}
```
