### ISSUE TITLE
session.StreamRawQueryInto include id in result (not metadata)

### ISSUE THREAD

**Issue by bobmcallan** [ravendb/ravendb-go-client#165]
When streaming results is there a way to include the ID in the Results and not as metadata. 

`
if err := json.Unmarshal(buffer.Bytes(), &m); err != nil {
	return output, err
}

eturn json.Marshal(m["Results"])
`

**Comment by ayende** [comment]
The whole idea of StreamRawQueryInto is that it will write the results directly from RavenDB to the `Writer` without anything in the middle.
You can have a projection in the query, that would transform the results, of course, but if you want to modify the data on the Go side, you'll need to skip the raw part and use normal streaming.
