### ISSUE TITLE
q = q.OrderBy("*** as double")

### ISSUE THREAD

**Issue by bobmcallan** [ravendb/ravendb-go-client#166]
Orderby as  a double results in string.

eg. q = q.OrderBy("user_id as double") => "from Users order by 'user_id as double', last_name, first_name"

Bob

**Comment by ayende** [comment]
You need to use `OrderByWithOrdering("user_id", "double")`, instead.

**Comment by ayende** [comment]
see: https://github.com/ravendb/ravendb-go-client/blob/f43327b57a88ab5931012a163c340f6e5856b602/document_query.go#L569

**Comment by bobmcallan** [comment]
Thanks, however implemented as suggested : 

q = q.OrderByWithOrdering("user_id", "double")
q = q.AddOrder("last_name", false)
q = q.AddOrder("first_name", false)

result: from Users order by user_id, last_name, first_name

Bob

**Comment by bobmcallan** [comment]
Worked it out..  CAPS for DOUBLE

package ravendb

type OrderingType = string

const (
	OrderingTypeString       = "STRING"
	OrderingTypeLong         = "LONG"
	OrderingTypeDouble       = "DOUBLE"
	OrderingTypeAlphaNumeric = "ALPHA_NUMERIC"
)

Thanks, 
Bob
