### ISSUE TITLE
Add Reference Collection to IndexCreationTask

### ISSUE THREAD

**Issue by bobmcallan** [ravendb/ravendb-go-client#167]
Is it possible to add the Reference Collection option to the IndexCreationTask.

![image](https://user-images.githubusercontent.com/8773580/125799830-34c4e233-360d-426e-ba21-7e76ca5f71fd.png)

Why; preference on creating indexes (with code) when the a service starts, rather than manually.

**Comment by ayende** [comment]
Doesn't this already exists here ?

https://github.com/ravendb/ravendb-go-client/blob/master/index_definition.go#L14

**Comment by bobmcallan** [comment]
OutputReduceToCollection does, however not "Create References to Results Collection".

**Comment by ayende** [comment]
Fixed now, you are correct
