### ISSUE TITLE
Ravendb tag/attribute (for Document ID or ?? ) on Structs

### ISSUE THREAD

**Issue by bobmcallan** [ravendb/ravendb-go-client#194]
To ensure consistant document create and id, is is possible to identify the id/key of the document with an tag/attribute?

**Example** 
```
type Type struct {
	ID          string      `json:"id"`
	Scope       []string    `json:"scope"`
	Name        string      `json:"name"`
}

Inserting this document creates =>
{
    "Id": "Types-737-A",
    "id": "Types-737-A",
    "name": "6af398b7-d8b3-4617-8293-21813de48893",
    "scope": null,
} 
```

**Solution**

Add a ravendb attribute to link the document id

```
type Type struct {
	Id          string      `json:"id" **ravendb**:"ID"`
	Scope       []string    `json:"scope"`
	Name        string      `json:"name"`
}
```

Also

```
type Type struct {
	TypeId          string      `json:"type_id" ravendb:"ID"`
	Scope       []string    `json:"scope"`
	Name        string      `json:"name"`
}
```

**Comment by ayende** [comment]
Not via an attribute, but you can do that using `DocumentIDGeneratorFunc`, that can inspect the document and use whatever field you want as the document key. 

https://github.com/ravendb/ravendb-go-client/blob/8c32f0ab1fe37e2c883ed3218ef1163a74736c85/document_conventions.go#L175

That said, the logic for this is here:

https://github.com/ravendb/ravendb-go-client/blob/8c32f0ab1fe37e2c883ed3218ef1163a74736c85/reflect.go#L90

It would be simple to add a func to customize that.

**Comment by bobmcallan** [comment]
I currently use that method, to Title case the ID (eg. Types-2145-A), however this may be just a my view of things.

If I created an entity such: 

type Type struct {
	ID          string      `json:"type_id"`
	Scope       []string    `json:"scope"`
	Name        string      `json:"name"`
}

The Ravendb UI documents view, shows the Id and type_id. The fields have the same detail ("Types-2145-A") however, can I assume that id == type_id.

**Comment by bobmcallan** [comment]
RavenUI Display.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/8773580/161928706-e19b8cea-4b7c-4325-97eb-daea6e984dd0.png">

**Comment by ayende** [comment]
That is just a UI structure, I think. The `id` property should actually be removed by the serializer, so you won't have this duplicatieon.
If you look at the actual document, there isn't an `Id` property thre.

**Comment by bobmcallan** [comment]
Thanks. Understood.
