### ISSUE TITLE
How to handle concurrency with document updates

### ISSUE THREAD

**Issue by dbblackdiamond** [ravendb/ravendb-go-client#199]
Hi,

I am using RavenDB as the backend for a mobile application and so far I am very pleased with the performance and the ease of use. The middleware for the application is built in go, hence why I am using the go client. One issue I have run into is how to handle concurrency with document updates with the go client. 
According to the RavenDB documentation, this is normal handled by setting `session.Advanced.UseOptimisticConcurrency = true`, which should result in a concurrency exception if another process is trying to update a document that has already been loaded in another session. I was looking through the ravendb-go-client documentation and can't find that ability, hence my question: how do I handle optimistic locking using the ravendb-go-client?

**Comment by ayende** [comment]
You are looking for this, I think:
https://github.com/ravendb/ravendb-go-client/blob/f43327b57a88ab5931012a163c340f6e5856b602/document_conventions.go#L27

You can set that once for the entire system.

You can also control that on a per document basis using:

https://github.com/ravendb/ravendb-go-client/blob/f43327b57a88ab5931012a163c340f6e5856b602/in_memory_document_session_operations.go#L645

**`StoreWithChangeVectorAndID`**

**Comment by dbblackdiamond** [comment]
Thank you for the quick response, but how does `StoreWithChangeVectorAndID` work? Do you have examples on how to use it? I have tried finding some and can't.

**Comment by ayende** [comment]
See here: 
https://ravendb.net/learn/inside-ravendb-book/reader/4.0/3-document-modeling#concurrency-control

This is equivalent to:

`session.Store(entity, changeVector);` 

Since Go doesn't have method overloading.

It means that we need to tell the session that it should fail to `SaveChanges()` if the expected change vector isn't a match on the server side.
