### ISSUE TITLE
Change in bool property not detected

### ISSUE THREAD

**Issue by dbblackdiamond** [ravendb/ravendb-go-client#200]
Hi,

I have a document with bool properties and when I try to update them, the changes are not detected and therefore not saved. 
Here is the document:
```
{
    "registration": [
        {
            "category": "Youth",
            "constraint": "",
            "entryfee": 40,
            "entryfeesreceived": false,
            "entryfeessent": false,
            "horseid": "horses/XEkxok9CmvMQYJc7Sg3foA",
            "horsename": "horse 4",
            "horserank": 0,
            "jp1run": false,
            "jp2run": true,
            "multihorses": false,
            "position": 0,
            "riderid": "users/kowEVMzEBtHxFRAe4V88Co",
            "ridername": "Awesome Rider 4",
            "roll": false
        }
],
}
```
If I try to update the property `entryfeessent`, it doesn't get detected.
Here is the code to update it:
```
func JackpotEntryFeesSent(jackpotId string, entries []*Entry, store *ravendb.DocumentStore) (*Jackpot, error) {
	var jackpot *Jackpot

	session, err := store.OpenSession("")
	if err != nil {
		log.Printf("JackpotEntryFeesSent:\tError opening session, err = &v", err)
		return jackpot, err
	}
	defer session.Close()

	err = session.Load(&jackpot, jackpotId)
	if err != nil {
		log.Printf("JackpotEntryFeesSent:\tError loading jackpot %s, err = &v", jackpotId, err)
		return jackpot, err
	}
	for _, sentEntry := range entries {
		for idx := range jackpot.Registration {
			if sentEntry.RiderId == jackpot.Registration[idx].RiderId && sentEntry.HorseName == jackpot.Registration[idx].HorseName && sentEntry.Category == jackpot.Registration[idx].Category {
				jackpot.Registration[idx].EntryFeesSent = sentEntry.EntryFeesSent
				break
			}
		}
	}
	log.Printf("JackpotEntryFeesSent:\tSaving updated jackpot")
	err = session.Store(jackpot)
	if err != nil {
		log.Printf("JackpotEntryFeesSent:\tError updating jackpot %s, err = %v", jackpot.EventId, err)
		return jackpot, err
        }
	err = session.SaveChanges()
	if err != nil {
		log.Printf("JackpotEntryFeesSent:\tError saving changes, err = %v", err)
		return jackpot, err
	}

	log.Printf("JackpotEntryFeesSent:\tSaved jackpot = %v", jackpot)
	return jackpot, nil
}
```

If I check the value for that `entry` in the `registration` array before the `session.Store`, it has the right value, but when I check the value in Studio, it still shows the old value. It is like the Go client doesn't detect that the `bool` value has changed. I have tried with a string value and if I don't change the value, the Go client doesn't update the database as it seems to figure out that the string value hasn't changed. I have tried with all the `bool` properties and I have the same issue. 

The other thing I have tried is to update one of the `string` values in the document at the same time and, when I do that, the `bool` value does get updated.

Thoughts?

Thanks a lot,
Bertrand.

**Comment by ayende** [comment]
Can you create a stand alone test reproducing this?
We need to see your entity and the entire behavior to be able to narrow down exactly what is going on.

**Comment by dbblackdiamond** [comment]
Let me see if I can put a quick stand alone test to reproduce this.

**Comment by dbblackdiamond** [comment]
> Can you create a stand alone test reproducing this? We need to see your entity and the entire behavior to be able to narrow down exactly what is going on.

Did you manage to take a look at the stand alone test i posted to reproduce the behaviour?

**Comment by dbblackdiamond** [comment]
> Can you create a stand alone test reproducing this? We need to see your entity and the entire behavior to be able to narrow down exactly what is going on.

Did you have a chance to take a look at the code I posted?

**Comment by ayende** [comment]
Fixed now
