### ISSUE TITLE
How to delete all the documents in a database

### ISSUE THREAD

**Issue by dbblackdiamond** [ravendb/ravendb-go-client#211]
Hi,

I have a need to programatically delete all the documents in a database. I have created an index that includes all the documents, called `AllDocuments` in the database and ravendb seems to have a function called `DeleteByQuery`, which could take the `from AllDocuments` query and delete all the documents matching that query. Unfortunately, I can't find a similar function in the Go module. I have found a `DeleteByQueryOperation` type, which references the `DeleteByIndexCommand` type, but I can't figure out how to use it.

I have looked at the ravendb doc and it shows the following code: 
```
// Define the delete by query operation, pass an RQL querying a collection
var deleteByQueryOp = new DeleteByQueryOperation("from 'Orders'");

// Execute the operation by passing it to Operations.Send
var operation = store.Operations.Send(deleteByQueryOp);

// All documents in collection 'Orders' will be deleted from the server.
```
I have tried to replicate the code in golang like this:
```
	query := ravendb.NewIndexQuery("from AllDocuments")
	deleteByQueryOps, err := ravendb.NewDeleteByQueryOperation(query, nil)
	if err != nil {
		return err
	}
	err = store.Operations().Send(deleteByQueryOps)
```
but it gives me an error message saying that `Send` needs different parameters, so at this point, I am not sure what to do. 
I know I could get the docs for each collection and load them and delete them one by one, but it feels that there should be a better way.

Have I missed something or am I over complicating this?
Thank you for the help in advance,
Bertrand.

**Comment by maciejaszyk** [comment]
Hi,
When you want to run query with a static index you have to add the `index` keyword.
```go
	query := ravendb.NewIndexQuery("from index AllDocuments")
```

Regarding the exception from the `Send` method, it takes two parameters, but you can put `nil` as parameter for `sessionInfo`:
```go
	err = store.Operations().Send(deleteByQueryOps, nil)
```

The whole example is available here:
https://github.com/ravendb/ravendb-go-client/blob/2b87f37fe4272af1cd41bd0dfe586f747f24b92e/tests/delete_by_query_test.go#L14-L57
