### ISSUE TITLE
Go cleanup: move to master branch so that godoc will work

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#26]
The canonical place for API docs is https://godoc.org/github.com/ravendb/ravendb-go-client

However, godoc doesn't support non-master branches like v4.0

Also, the emerging modules support (`go mod`) that will debut in upcoming go 1.11 relies on tagging versions. We Should follow those ecosystem conventions.

**Comment by ppekrol** [comment]
We want to host docs here: https://ravendb.net/docs/article-page/4.0/csharp
which comes from https://github.com/ravendb/docs

We do not want to split documentation into multiple places. And if 'godoc' only supports 'master' then it does not make sense having documentation there, especially when we will have v4.1, v4.2, v5.0 etc in the future

**Comment by kjk** [comment]
This is about expectations of community and being a part of greater ecosystem.

The modules system coming up in Go assumes master branch and using git tags for marking versions, not git branches.

If this code base doesn't follow those conventions then almost certainly things will break i.e. the standard tools won't be able to handle this code.

Similarly for docs. 

Go has a standard way of documenting the API directly in code. godoc.org is a canonical place where people go to see those docs. If the docs are not there, people will be confused.

The docs at https://ravendb.net/docs/article-page/4.0/csharp are an addition to API docs generated from code, but not a replacement.

**Comment by ppekrol** [comment]
I think that we cannot go with 1 branch, how we will maintain fixes for v4.x client when code there will already be v5.x? Where the v4.x documentation will go?

C# also supports automatic documentation directly from code, but we didn't go that way because most of the methods without a proper context, explanation, examples and links to other articles would not be that handy.

Can we create in master branch a page that with summary and brief introduction? Something similar to https://www.npmjs.com/package/ravendb ?

**Comment by kjk** [comment]
https://research.swtch.com/vgo-module and https://github.com/golang/go/wiki/Modules#version-selection describes how the Go tooling around version will work.

It's compatible with having maintance branches for older versions with the following scheme:
* master branch is where the latest version is e.g. v4
* tagging is how releases are made e.g. tag 4.0.1, 4.1, 4.2.3 etc.
* for bugfixes for older version, e.g. 3.x, have a branch 3.x and make bugfixes there. To make a release, tag a specific commit with 3.x.y

**Comment by ppekrol** [comment]
Hi @kjk 

We can move to master branch for the API docs.

P.

**Comment by kjk** [comment]
Moved to a master branch.
