### ISSUE TITLE
DurationSerializationTest

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#30]
In go, `time.Duration` is just an `int64` which serializes as int (https://goplay.space/#RneadN2UM67)

In Java, there's custom serialization for `Duration`.

Is it a requirement?

We can emulate that by defining `ravendb.Duration` type with custom Json serialization and tell users to use it instead of `time.Duration`, when necessary.

**Comment by ayende** [comment]
For handling duration, yes.

**Comment by ayende** [comment]
Only if you want to do indexing on that, though.

**Comment by kjk** [comment]
If duration is serialized as a number (i..e json float), wouldn't indexing work as well?

**Comment by ayende** [comment]
It would, but your queries will need to query on that.
The major issue is if you want to do something like:

`(doc.Start - doc.End).TotalHours`

In your index. In that case, if you serialize as `10:00:00` it will work properly.

**Comment by ppekrol** [comment]
Sending an int/long for fields that are TimeSpan in C# will also work IIRC. It must be in milliseconds.

**Comment by kjk** [comment]
implemented in https://github.com/ravendb/ravendb-go-client/commit/9312202341440b6e3a76cbde77e2d139fe9153af
