### ISSUE TITLE
API cleanup: replace usage of *StringSet with []string

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#31]
I imagine using a set is meant to ensure no duplicate strings.

`StringSet` is not very Go-ish.

We can get the same result by keeping them as `[]string` and doing `stringArrayRemoveDups(a []string, s string) []string` right before the use. Overall it would probably be even faster than using `StringSet`.

If possible, we should replace all uses of StringSet with such a scheme.

**Comment by ayende** [comment]
That is find to do yes. There isn't really a meaning to ensuring uniqueness in this situation

**Comment by kjk** [comment]
Usages to fix:
* [ ] `AbstractDocumentQuery.includes`
* [ ] `AbstractIndexCreationTask.IndexSuggestions`
* [ ] `InMemoryDocumentSessionOperations._knownMissingIds`
* [ ] `IndexDefinitionBuilder.suggestionsOptions`
* [ ] `IndexDefinition.Maps`
* [ ] `TermsQueryResult.Terms`
