### ISSUE TITLE
API cleanup: can IndexDefinition.Priority etc. be a string and not *string

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#32]
Java client JSON serializer seems to always send unset fields as 'null'. In JSON, not sending the field is mostly the same i.e. to the server:
```json
{
  Priority: null,
}
```
should be the same as:
```json
{
}
```

In Go I was matching Java 'null' serialization by using `*string` for fields like `IndexDefinition.Priority` but it's awkward.

It would be better to use `string` and `,omitempty` annotation to not send the field when value is empty string.

The question is: can we a guarantee that the server will handle 'null' value and "not present" in exactly the same way?

Similar is `IndexDefinition.Fields` where empty values are sent as `{}` instead of not being sent at all.

**Comment by ayende** [comment]
Yes, the server will gracefully handle missing values and consider them as `null`

**Comment by kjk** [comment]
Done.
