### ISSUE TITLE
API cleanup: consider renaming to raven or rdb

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#34]
Go style favors short package names. For example, MongoDB driver is `mgo`, PosatgreSQL driver is `pg` etc.

Partly it's because user code has to prefix every type/method with package name. Shorter name => less typing.

For that reason, it would make sense to rename package to `rdb` or `raven`.

It's unlikely that other `rdb` packages would be used in the same program (https://godoc.org/?q=rdb).

Related: Go best practice is that repository name is the same as top-level package name. So if package name is `rdb`, repository name should be https://github.com/ravendb/rdb

**Comment by ppekrol** [comment]
Let's go with `ravendb` (matches Java and NodeJS).
Repository name should stay as is.
