### ISSUE TITLE
API cleanup: hide implementation structs

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#35]
I assume that e.g. `IndexDefinitionBuilder` is an implementation detail and not meant to be accessed by users of the library.

If that is the case, it should be renamed to `indexDefinitionBuilder` so that it's not accessible outside of the package.

I assume there are more types like that. I can make guesses but someone with knowledge of the intent of Java client code should go over all structs and decide if they are public or just an implementation detail.

**Comment by kjk** [comment]
Go doesn't have the equivalent of Linq.

If it's about making it usable by the users of library, then we would have to make the fields of `IndexDefinitionBuilder` public.

Going further, given that `IndexDefinitionBuilder` and AbstractIndexCreationTask` have almost identical data, we should extract common part (e.g. as `IndexDescription`) and maybe replace the class `IndexDefinitionBuilder` with a function `CreateIndexDefinitionFromDescription`.

**Comment by ayende** [comment]
ok

**Comment by kjk** [comment]
I've hidden those that are obviously private.
