### ISSUE TITLE
Cleanup: optimize how commands work

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#36]
This is a bonus.

Currently the pattern for constructing command `Foo` is:
* in `NewFooCommand` we create `FooCommand` object where we store all the arguments
* in `FooCommand.CreateRequest` we create uri and request body based on stored arguments and `ServerNode`

Observation: we can move all that work from `CreateRequest` to `NewFooCommand`. In most (all) cases `CreateRequest` can be a generic one which replaces known patterns (e.g. `{url}` and `{db}` in the url with `ServerNode.URL` and `ServerNode.Database`.

It's less code and should be slightly faster.

Doesn't require changing API.

Here's an example for`NextHiLoCommand`: https://www.diffchecker.com/yjsuwfUn
Saves 12 lines (out of ~50).

This is how it worked initially when I was working from Python client. When I switched to following Java client I went for matching Java structure.

This optimization applies to Java code too.

**Comment by kjk** [comment]
I don't see a problem for most (all?) commands.

The url can be re-created multiple times. In this scheme we do substitute server url and database on `CreateRequest`.

The request body that is `[]byte` can be sent multiple times.

The only issue I can see is where the request body is an `io.Reader` that can only be read once. But then this case is probably broken right now too because I don't think it would work without special code to handle it and I don't think I put such special code.

**Comment by ayende** [comment]
Okay

**Comment by kjk** [comment]
low priority so table it for now
