### ISSUE TITLE
re-authorize appveyor to access github repo

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#42]
Appveyor builds started failing like this: https://ci.appveyor.com/project/ravendb/ravendb-go-client/build/4.0.56

Apparently this can be fixed by re-authorizing Appveyor to access github repo (https://help.appveyor.com/discussions/problems/11287-the-build-phase-is-set-to-msbuild-mode-default-but-no-visual-studio-project-or-solution-files-were-found), but I don't have permissions for that.

**Comment by ppekrol** [comment]
It looks like it is working now... Maybe some temporary issue.

https://ci.appveyor.com/project/ravendb/ravendb-go-client/build/4.0.57
