### ISSUE TITLE
API cleanup: smaller API surface for Where queries

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#43]
Steal https://godoc.org/cloud.google.com/go/firestore#Query.Where api.

Replace `WhereEquals`, `WhereNotEquals` etc. with `Where(what, op string, val)`.

E.g. `WhereEquals("foo", "bar")` becomes `Where("foo", "=", "bar")`. Valid ops: `=`, `==` (same as `=`), `!=`, `>`, `>=`, `<`, `<=`.

**Comment by ayende** [comment]
That pushes us away from the standard interface we have

**Comment by ppekrol** [comment]
Let's keep our API as close to Java/C#/Node as possible.
