### ISSUE TITLE
API cleanup: replace `FooExact()` query methods with `Exact()` modifier.

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#44]
There are multiple query methods with `exact bool` arg. Due to lack of over-loading, I had to make variants of those APIs names as `WhereIn` and `WhereInWithExact`.

Replace all `*Exact` methods with a single `Exact()` method that modifies last token by setting `exact = true`.
I.e.: `q.WhereIn(...).Exact()`.
It would panic if last token is not valid for `Exact()`.

**Comment by ppekrol** [comment]
Let's go with `q.WhereIn(...).Exact()` we already have similar method like `.Boost` that do the same thing.
