### ISSUE TITLE
Improve DatabaseChanges APIs

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#57]
API should be strongly typed ie. instead of returning `IChangesObservable` it should return strongly typed version.

It's even more awkward with the `IChangesObservable` => `IObserver`.

A simpler and strongly typed API would be:
```
func (d *DatabaseChanges) SubscribeForIndex(indexName string, onNext func(*IndexChange), onError func(error), onComplete func()) CleanCloseable
```

**Comment by ayende** [comment]
Question, wouldn't this actually be more idiomatic if we just exposed a channel that the user can listen on?

**Comment by kjk** [comment]
Agreed it would be even better.

We don't need onComplete as that can be signaled by closing the channel.

To support reporting errors we would have to add `Err error` field to `IndexChange`, `DocumentChange` and `OperationStatusChange`.

The API would then become:
```
func (d *DatabaseChanges) ForIndex(indexName string) (chan *IndexChange, CleanCloseable)
```

**Comment by kjk** [comment]
For now I went with `func (c *DatabaseChanges) ForIndex(indexName string, cb func(*IndexChange)) (CancelFunc, error)` style.

It can be easily changed to returning a channel. To be decided.
