### ISSUE TITLE
ravendb-go-client setup

### ISSUE THREAD

**Issue by Generalomosco** [ravendb/ravendb-go-client#59]
I'm basically new to Golang also to ravendb and no special lame documentation like others.

Can i please get the way to make  ravendb-go-client connection (get doc, insert and update) to my installed revandb server?

**Comment by ayende** [comment]
You can follow the usual manner of setting up RavenDB, as specified in the docs.
From then, you'll use:

```
store := ravendb.NewDocumentStoreWithUrlsAndDatabase(urls, name)
store.setDatabase(database)
store.initialize()
```
To set things up.

```
session, err := store.OpenSession()
if err != nil:
      return nil, err
defer session.Close()
user := &User{}
user.setName("Grisha")
err = session.StoreWithID(user, documentId)
if err != nil:
   return nil, err
err = session.SaveChanges()
if err != nil:
   return nil, err
return user.getId(), nil
```

**Comment by Generalomosco** [comment]
Thanks a lot! I appreciated
