### ISSUE TITLE
Updating document

### ISSUE THREAD

**Issue by Generalomosco** [ravendb/ravendb-go-client#62]
If don't know if i use this kind of method to update document if it is going to erase new updates after `session.Advanced().Load` loaded before new update comes in!

Why i want to use this is because ravendb don't update unexisting object from path.

```
var bo *Bodyy
  ff := session.Advanced().Load(&bo,"NewCollection/0000000000000000185-A")
  if ff != nil{
   fmt.Println(ff)}
  
  bo.Doc=map[string]string{
			"Ohio":       "Columbus",
			"Utah":       "Salt Lake City",
			"Texas":      "Austin",
			"California": "Sacr..",
		}
		err = session.SaveChanges()
```

**Comment by ayende** [comment]
Loading a document that was already loaded is a noop, basically.
You'll get back the previous loaded instance.
