### ISSUE TITLE
Realtime with query 

### ISSUE THREAD

**Issue by Generalomosco** [ravendb/ravendb-go-client#66]
Is there anyway i can queue realtime with query option in golang just as java [here](https://ravendb.net/docs/article-page/4.1/csharp/client-api/session/querying/how-to-stream-query-results)

```
IQueryable<Employee> query = session
    .Query<Employee, Employees_ByFirstName>()
    .Where(x => x.FirstName == "Robert");

IEnumerator<StreamResult<Employee>> results = session.Advanced.Stream(query);

while (results.MoveNext())
{
    StreamResult<Employee> employee = results.Current;
}
```

But golang ` session.Advanced.Stream(...)` don't accept query variable as argument but only accept startWith as argument which look as below..

 ```
args := &ravendb.StartsWithArgs{
				StartsWith: "users/",
			}
			reader, err := session.Advanced().Stream(args)
			for {
			var user *User
				_, err = reader.Next(&user)
				if err == io.EOF {
					err = nil
					break
				}
			}
```

What i want is if i can make this below as stream

```
 q := session.Advanced().DocumentQueryAllOld(reflect.TypeOf(&models.List{}), "", "users", false)
 q = q.WhereEquals("name", "Wisdom")
 q = q.WhereGreaterThan("ic", 6)
```
  
So if i can be getting `q` results in realtime or if i can add query option to session.Advanced().Stream(args)

**Comment by kjk** [comment]
Please make sure that you're using `master` branch (v4.0 used to be a main branch but is not behind master).

In master there is:
```
func (s *DocumentSession) StreamQuery(query *IDocumentQuery, streamQueryStats *StreamQueryStatistics) (*StreamIterator, error) {
```
and
```
func (s *DocumentSession) StreamRawQuery(query *IRawDocumentQuery, streamQueryStats *StreamQueryStatistics) (*StreamIterator, error) {
```
which should be the functionality you're looking for.

**Comment by kjk** [comment]
Closing as the functionality asked seems to be implemented.
