### ISSUE TITLE
Make query realtime onChanges for subscribers

### ISSUE THREAD

**Issue by Generalomosco** [ravendb/ravendb-go-client#67]
I make a real-time query to listen to changes in a collection, but i don't know if this is advisable for production because it like it look silly or Okay?
 ```
 {
		changesList := make(chan *ravendb.DocumentChange, 8)

		changes := Conn.RavStore.Changes()
		changes.EnsureConnectedNow()

		observable, err := changes.ForDocumentsInCollection("user")
    
    
	if err != nil {
		fmt.Println("ccccEEER",err.Error())
	}

		{
			action := func(v interface{}) {
				change := v.(*ravendb.DocumentChange)
				changesList <- change
			}
			observer := ravendb.NewActionBasedObserver(action)
			subscription := observable.Subscribe(observer)
      ics:=0
      for{
        ics++
			select {
			case documentChange := <-changesList:
				fmt.Println("cccc", documentChange)
        
		q := session.Advanced().DocumentQueryAllOld(reflect.TypeOf(&models.List{}), "", "user", false)
         q = q.WhereEquals("Doc.type", "member")
        q.ToList(&queryResult)
  
        fmt.Println("Finally watching result: ",queryResult)

			//case <-time.After(time.Second * 27):}
      }
			subscription.Close()
		}

	}
```

**Comment by ayende** [comment]
What is it that you are trying to do with this?

**Comment by Generalomosco** [comment]
I'm using it for Multi Tenancy where each customer will also have metered clients operations, so the query can be used for anything, it is dynamic

**Comment by ayende** [comment]
What you basically want is to be able to get updates for a query, right?
Is there a reason not to use subscriptions?

**Comment by ayende** [comment]
Subscriptions are _the_ recommended way to do long term processing of queries.

Changes are meant more to do things like "someone changed this document you are working on" or "there are new results for the query you are look at".

**Comment by Generalomosco** [comment]
Yes, What i did is that i make a subscription to a collection and i immediately make a query when changes occurred in the subscribed collection

**Comment by ayende** [comment]
Great
