### ISSUE TITLE
Golang client status

### ISSUE THREAD

**Issue by piotrkochan** [ravendb/ravendb-go-client#69]
The question is, what is the status of ravendb-go-client? I can tell that C# or NodeJS Clients are very useable but how it is with this Golang client? I see the only one code example have comment and it says that example does not work beacuse of some issue: https://github.com/ravendb/ravendb-go-client/blob/master/examples/read/main.go#L88

**Comment by kjk** [comment]
It's alpha state meaning there are bugs and some APIs might change but a lot works already. See tests (https://github.com/ravendb/ravendb-go-client/tree/master/tests)  for examples of functionality that works.

I need to write more examples.
