### ISSUE TITLE
Fix appveyor 10 min timeout

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#70]
Sometimes appveyor builds fail because they take more than 10 mins (e.g https://ci.appveyor.com/project/ravendb/ravendb-go-client/builds/20914244)

According to docs the limit on AppVeyor is 1 hr so this shouldn't be happening.

The only reason for this that I can think of is that lower limit is set in settings UI (https://ci.appveyor.com/project/ravendb/ravendb-go-client/settings, field "Build timeout, minutes").

I don't have permissions for that on AppVeyor so could you guys look into it?

**Comment by gregolsky** [comment]
It's not set (blank). When I try to set it, it complains with the following:
> Custom build timeout works with private build clouds only. Contact AppVeyor team to learn more about private build clouds.

Thoughts?

**Comment by kjk** [comment]
Oops, silly me. That's actually a timeout of `go test`, not AppVeyor. Will fix.
