### ISSUE TITLE
Match Java's order for mult-insert

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#71]
Not sure if that's required but there certainly are tests that rely on this behavior (e.g. `query_queryLazily`).

Consider this multi-object insert:

```go
err = session.StoreWithID(user1, "users/1")
err = session.StoreWithID(user2, "users/2")
err = session.StoreWithID(user3, "users/3")
err = session.SaveChanges()
```

In Java, in JSON for `bulk_docs` command, the objects in `Commands` array will always be in the same order.

In Go, because they are buffered in a `map` and a map has randomized traversal order, they will be in random order.

This affects e.g. the order of results for search query (the server seems to return them in order they were sent in `bulk_docs` JSON).

We can achieve the same order as Java by buffering objects in a slice instead of a map.

When done for testing it we can undo the code in `query_queryLazily` that makes the check not sensitive to order.

**Comment by ayende** [comment]
Yes, we want to keep it in the same order
