### ISSUE TITLE
Ensure proper ravendb.Time serialization

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#78]
Make sure the way `Time` in `time.go` serializes to JSON is always what the server can handle.

Specific issues:
* does it have to be UTC?
* 6 or 7 micro-second part (see #77 for more info)

Figure out if can fail with current serialization and if yes, fix the code and write a test.

Quest to ravendb team: is there a spec for server's serialization of `DateTime` values?

Is there a list of all server requests that contain `DateTime` values (so that I can audit Go client and make sure I always use the right type there)?

**Comment by ayende** [comment]
We use ISO 8601 for the dates.
The full format is: `yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffff`

**Comment by kjk** [comment]
I couldn't find a definitive grammar for ISO 8601 but I don't think it requires `.fffffff` to be exactly 7 digits (https://stackoverflow.com/questions/25842840/representing-fraction-of-second-with-iso-86012004).

Go (https://golang.org/src/time/time.go?s=36746:36789#L1214) uses RFC 3339 Nano format (https://golang.org/pkg/time/#pkg-constants) which is a subset of ISO 8601 (https://www.ietf.org/rfc/rfc3339.txt) which is up to 9 digits but removes trailing zeros so in practice in ends up with 6 or 7 digits.

The server doesn't seem to handle 6 digits in some scenarios (as described in #77)
