### ISSUE TITLE
Allow Delete(&e) ?

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#82]
When we load, we do:
```
var u *User
session.Load(&u, id)
```

When we delete, we need to do:
```
session.Delete(u)
```

However, it's easy for people to pattern-match and write:
```
session.Delete(&u)
```
which fails because those are not the same objects.

We could probably make it work easily: if we detect that object is of type `**struct`, we can re-run failed `Delete` with `*struct`. It'll be slower.

Is it worth it?

**Comment by ayende** [comment]
Yes, if this is something that users are likely to do , let's make it eaiser.

**Comment by kjk** [comment]
Ended up rejecting `**User` but returning (hopefully) specific error message.

We can relax this in the future.
