### ISSUE TITLE
Re-enable code coverage via codecov.io

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#93]
When I moved from working on kjk/ravendb-go-client to ravendb/ravendb-go-client, we lost code coverage reporting because the ravendb/ravendb-go-client is not registered with codecov.io.

I can't add repos I don't own, so please re-enable it by:
* login to https://codecov.io with GitHub credentials
* in the dashboard, add ravendb/ravendb-go-client repository

**Comment by ayende** [comment]
For some reason, I can't add ravendb to it. Maybe @ppekrol has any idea?

**Comment by kjk** [comment]
Is there are an error message? I just tested adding one of my repositories.

Also, when project is added, it'll show upload token, which must be set in travis ci as secret env variable (this is needed for `bash <(curl -s https://codecov.io/bash)` in `travis.yml` to work.

**Comment by ppekrol** [comment]
I will check that in more details on Thursday, but it looks like it does not support organization repositories very well. I do not see any repos for 'ravendb-bot', no teams, it is empty.

**Comment by kjk** [comment]
You might need to grant access to codeconv in GitHub settings (https://github.com/settings/connections/applications, find Codeconv).

**Comment by ppekrol** [comment]
I did that. I see Travis and AppVeyor on that list, so it looks good. Those are permissions that Codeconv requested.

**Comment by kjk** [comment]
It works now thanks. 

A minor thing: still thinks v4.0 is a default branch show the main page (https://codecov.io/gh/ravendb/ravendb-go-client) doesn't update coverage chart.

But it can be seen by visiting view for master branch (https://codecov.io/gh/ravendb/ravendb-go-client/branch/master)
